### PR TITLE
Start resource

### PR DESCRIPTION
**Pull request by SIHTAM-mp4**
Hello there is not a resource.lua or fxmanifest who can help me pls

### CODE REVIEW

**Comment by TanguyOrtegat** [comment]
Hello, i forked this resource, for people that knows javascript. Original post has been deleted unfortunatly ...

**Comment by SIHTAM-mp4** [comment]
Well how do i start this resource in fivem ?

**Comment by MonoChirito** [comment]
you dont. you can make the WHOLE fivem part integration yourself or just wait/die

**Comment by PhenixMortel** [comment]
> you dont. you can make the WHOLE fivem part integration yourself or just wait/die

:'(

**Comment by Bulle93230** [comment]
Then this script is useless... :x

**Pull request closed without merging**
